plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:
  "@aws-crypto/kms-keyring-node@*":
    dependencies:
      "@aws-crypto/material-management": "*"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
