compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@aws-crypto/kms-keyring-node@*":
    dependencies:
      "@aws-crypto/material-management": "*"

supportedArchitectures:
  {
    os: ["current", "darwin", "linux"],
    cpu: ["current", "x64"],
    libc: ["current", "glibc"],
  }

yarnPath: .yarn/releases/yarn-4.0.2.cjs
