compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: false

packageExtensions:
  "@artilleryio/sketches-js@*":
    dependencies:
      protobufjs: "*"
  "@aws-crypto/kms-keyring-node@*":
    dependencies:
      "@aws-crypto/material-management": "*"
  artillery-plugin-slack@*:
    dependencies:
      moment: "*"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
