compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@aws-crypto/kms-keyring-node@*":
    dependencies:
      "@aws-crypto/material-management": "*"
  "artillery-plugin-slack@*":
    dependencies:
      "moment": "*"
  "@artilleryio/sketches-js@*":
    dependencies:
      "protobufjs": "*"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.4.1.cjs
