import { Command, program } from "commander";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import * as prettier from "prettier";

import { R4, R4B, Resource } from "@iguhealth/fhir-types/versions";

import {
  createHash,
  getSearchParameterSearchParameter,
} from "../api/generate.js";
import { loadParameters } from "../api/load.js";
import { uri } from "@iguhealth/fhir-types/lib/generated/r4/types";

function generateCommands(command: Command) {
  command
    .command("canonical-map")
    .requiredOption("-o, --output <output>", "output file")
    .action(async (options) => {
      const r4Parameters = loadParameters(R4);
      const r4bParameters = loadParameters(R4B);
      const hash = await createHash(
        R4B,
        r4bParameters,
        await createHash(R4, r4Parameters),
      );

      mkdirSync(path.join(options.output, ".."), { recursive: true });
      writeFileSync(
        options.output,
        await prettier.format(
          `// Do not edit this file it has been generated via the CLI generate canonical-map command.
          import {SearchParameterCanonicalHash} from "../api/generate.js";
        export default ${JSON.stringify(hash, null, 2)} as SearchParameterCanonicalHash`,
          {
            parser: "typescript",
          },
        ),
      );
    });

  command
    .command("special-parameters")
    .requiredOption("-o, --output <output>", "output file")
    .action(async (options) => {
      const r4Parameters = (
        await getSearchParameterSearchParameter(R4, loadParameters(R4))
      ).reduce(
        (
          acc: Record<uri, Resource<R4, "SearchParameter">>,
          parameter: Resource<R4, "SearchParameter">,
        ) => {
          return { ...acc, [parameter.url]: parameter };
        },
        {},
      );

      const r4bParameters = (
        await getSearchParameterSearchParameter(R4B, loadParameters(R4B))
      ).reduce(
        (
          acc: Record<uri, Resource<R4B, "SearchParameter">>,
          parameter: Resource<R4B, "SearchParameter">,
        ) => {
          return { ...acc, [parameter.url]: parameter };
        },
        {},
      );

      mkdirSync(path.join(options.output, ".."), { recursive: true });
      writeFileSync(
        options.output,
        await prettier.format(
          `// Do not edit this file it has been generated via the CLI generate special-parameters command.
          import { uri } from "@iguhealth/fhir-types/r4/types";
          import { Resource, R4, R4B  } from "@iguhealth/fhir-types/versions";
        export default  { [R4]: ${JSON.stringify(r4Parameters, null, 2)}, [R4B]: ${JSON.stringify(r4bParameters, null, 2)} } as {[R4]: Record<uri, Resource<R4, "SearchParameter">>, [R4B]: Record<uri, Resource<R4B, "SearchParameter">>}`,
          {
            parser: "typescript",
          },
        ),
      );
    });
}

generateCommands(program.command("generate"));

await program.parseAsync();
