services:
  postgres:
    extends:
      file: services-compose.yml
      service: postgres
  redis:
    extends:
      file: services-compose.yml
      service: redis

  migration:
    image: ghcr.io/iguhealth/iguhealth/iguhealth:latest
    depends_on:
      - postgres
    environment:
      - SESSION_COOKIE_SECRETS=session_secret
      - FHIR_DATABASE_NAME=iguhealth
      - FHIR_DATABASE_HOST=postgres
      - FHIR_DATABASE_PORT=5432
      - FHIR_DATABASE_PASSWORD=postgres
      - FHIR_DATABASE_USERNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://localhost:3000
      - ADMIN_APP_REDIRECT_URI=http://*.localhost:3001

    command: ["migrate"]

  iguheath:
    image: ghcr.io/iguhealth/iguhealth/iguhealth:latest
    depends_on:
      - migration
      - redis
    environment:
      - SESSION_COOKIE_SECRETS=session_secret
      - FHIR_DATABASE_NAME=iguhealth
      - FHIR_DATABASE_HOST=postgres
      - FHIR_DATABASE_PORT=5432
      - FHIR_DATABASE_PASSWORD=postgres
      - FHIR_DATABASE_USERNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://localhost:3000
      - ADMIN_APP_REDIRECT_URI=http://*.localhost:3001
    ports:
      - "3000:3000"
    command: ["both"]

  admin:
    image: ghcr.io/iguhealth/iguhealth/admin-app:latest
    depends_on:
      - iguheath
    ports:
      - "3001:80"
    environment:
      - REACT_APP_FHIR_BASE_URL=http://localhost:3000
