services:
  postgres:
    extends:
      file: services-compose.yml
      service: postgres
  redis:
    extends:
      file: services-compose.yml
      service: redis

  iguheath:
    image: ghcr.io/iguhealth/iguhealth/iguhealth:latest
    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - redis

    environment:
      - SESSION_COOKIE_SECRETS=session_secret
      - FHIR_DATABASE_NAME=iguhealth;
      - FHIR_DATABASE_HOST=postgres
      - FHIR_DATABASE_PORT=5432
      - FHIR_DATABASE_PASSWORD=postgres
      - FHIR_DATABASE_USERNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://localhost:3000
      - ADMIN_APP_REDIRECT_URI=http://*.localhost:3001

    command: ["both"]
