services:
  postgres:
    extends:
      file: services-compose.yml
      service: postgres
  redis:
    extends:
      file: services-compose.yml
      service: redis

  iguheath-server: &iguhealth-server
    image: iguhealth/iguhealth-server:latest

    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - redis

    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379

  iguheath-worker: &iguhealth-server
    image: iguhealth/iguhealth-server:latest

    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - redis

    environment:
      - SESSION_COOKIE_SECRETS: string;
      - FHIR_DATABASE_NAME: string;
      - FHIR_DATABASE_HOST: string;
      - FHIR_DATABASE_PORT: string;
      - FHIR_DATABASE_PASSWORD: string;
      - FHIR_DATABASE_USERNAME: string;
      - REDIS_HOST: string;
      - REDIS_PORT: string;
      - API_URL: string;
      - ADMIN_APP_REDIRECT_URI?: string;

      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379

    command: ["entrypoint", "worker"]
