services:
  redis:
    image: redislabs/redismod

    ports:
      - 6379:6379

  postgres:
    image: postgres:16.3

    ports:
      - 5432:5432

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=iguhealth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
