/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://datatracker.ietf.org/doc/html/rfc7662#section-2.1
 */
export interface OAuth2TokenIntrospectionBody {
  /**
   * Token to introspect.
   */
  token: string;
}
