/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OAuth2TokenBody =
  | {
      /**
       * The grant type used in the initial request.
       */
      grant_type: "authorization_code";
      /**
       * The authorization code received from the authorization server.
       */
      code: string;
      /**
       * The redirect URI used in the initial request.
       */
      redirect_uri: string;
      /**
       * The code verifier used in the initial request.
       */
      code_verifier: string;
      /**
       * The client ID used in the initial request.
       */
      client_id: string;
    }
  | {
      /**
       * The grant type used in the initial request.
       */
      grant_type: "refresh_token";
      /**
       * The refresh token used to obtain a new access token.
       */
      refresh_token: string;
      /**
       * The scope of the access request.
       */
      scope?: string;
    }
  | {
      /**
       * The grant type used in the initial request.
       */
      grant_type: "client_credentials";
      /**
       * The client ID used in the initial request. May also be included in the Basic header.
       */
      client_id?: string;
      /**
       * The client Secret used in the initial request. May also be included in the Basic header.
       */
      client_secret?: string;
    };
