name: Workflow for Codecov example-javascript
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: typos-action
        uses: crate-ci/typos@v1.15.0
        # https://github.com/crate-ci/typos/blob/master/docs/github-action.md
        with:
          config: ./typos.config.toml

      - name: Set up Node 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Compile
        run: npx nx run-many -t build
      - name: Run tests and collect coverage
        run: bun test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
