name: Publish Package to npmjs
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: EnableCorePack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - run: yarn workspaces foreach -t run publish
        timeout-minutes: 10
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
