name: Docker Images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: iguhealth/iguhealth
  ADMIN_APP_IMAGE_NAME: iguhealth/admin-app

jobs:
  server:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Apply versioning
        run: yarn version apply -R --all

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - id: package_json_version
        run: |
          content=`cat ./packages/server/package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - name: Build and Publish Image
        run: |
          IMAGE_NAME=$(echo $SERVER_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{fromJson(steps.package_json_version.outputs.packageJson).version}}")
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build . \
           --file docker/server/server.dockerfile \
           --tag $IMAGE_ID:$VERSION \
           --tag $IMAGE_ID:latest \
           --label "runnumber=${GITHUB_RUN_ID}" \
           --platform linux/amd64,linux/arm64 \
           --push

  admin-app:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Apply versioning
        run: yarn version apply -R --all

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - id: package_json_version
        run: |
          content=`cat ./packages/admin-app/package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - name: Build and Publish Image
        run: |
          IMAGE_NAME=$(echo $ADMIN_APP_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Pulls image from admin-app package.json which is set in previous step.
          VERSION=$(echo "${{fromJson(steps.package_json_version.outputs.packageJson).version}}")
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build . \
           --file docker/admin-app/admin-app.dockerfile \
           --tag $IMAGE_ID:$VERSION \
           --tag $IMAGE_ID:latest \
           --label "runnumber=${GITHUB_RUN_ID}" \
           --platform linux/amd64,linux/arm64 \
           --push
